### ISSUE TITLE
[Security] Workflow main.yml is using vulnerable action wemake-services/wemake-python-styleguide

### ISSUE THREAD

**Issue by Ale0x78** [Digital-Learning-fur-Schuler/snap-school#13]
The workflow main.yml is referencing action wemake-services/wemake-python-styleguide using references 0.14.0. However this reference is missing the commit [7528a610538e9d215b39b4ad21fa17c1c6c01b3d](https://github.com/wemake-services/wemake-python-styleguide/commits/7528a610538e9d215b39b4ad21fa17c1c6c01b3d) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by oli-ver** [comment]
Thanks @Ale0x78, I upgraded wemake-python-styleguide to the latest version 0.16.0
